#!/bin/bash

# Given two integers, and , find their sum, difference, product, and quotient.

read value1
read value2

expr $value1 + $value2
expr $value1 - $value2
expr $value1 \* $value2
expr $value1 / $value2
